"""Add task_id and status columns to generated_voice table

Revision ID: 040c358a5fc6
Revises: add_voice_tables
Create Date: 2025-07-17 17:35:03.225188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '040c358a5fc6'
down_revision = 'add_voice_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # generated_voice 테이블에 컬럼 추가
    op.add_column('generated_voice', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.add_column('generated_voice', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('generated_voice', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # s3_url과 s3_key를 nullable로 변경 (비동기 작업 시 처음엔 null이므로)
    op.alter_column('generated_voice', 's3_url',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('generated_voice', 's3_key',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 컬럼 삭제
    op.drop_column('generated_voice', 'updated_at')
    op.drop_column('generated_voice', 'status')
    op.drop_column('generated_voice', 'task_id')
    
    # s3_url과 s3_key를 다시 not null로 변경
    op.alter_column('generated_voice', 's3_key',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('generated_voice', 's3_url',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
