"""add influencer_age_group to AIInfluencer

Revision ID: 0e00f2507597
Revises: 1266934d4202
Create Date: 2025-06-30 17:52:27.586022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e00f2507597'
down_revision = '1266934d4202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AI_INFLUENCER', sa.Column('influencer_age_group', sa.Integer(), nullable=True, comment='AI 인플루언서 연령대'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AI_INFLUENCER', 'influencer_age_group')
    # ### end Alembic commands ###
