"""ensure influencer_tone in AIInfluencer

Revision ID: 1266934d4202
Revises: 7fda0eb4ca0c
Create Date: 2025-06-30 17:51:57.993786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1266934d4202'
down_revision = '7fda0eb4ca0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AI_INFLUENCER', sa.Column('influencer_tone', sa.Text(), nullable=True, comment='AI 인플루언서 말투/톤'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AI_INFLUENCER', 'influencer_tone')
    # ### end Alembic commands ###
