"""add vllm_task_id to batch_key

Revision ID: 20250708225105
Revises: g09c1d7fgb46
Create Date: 2025-07-08 22:51:05

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250708225105'
down_revision = 'g09c1d7fgb46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BATCH_KEY', sa.Column('vllm_task_id', sa.String(length=255), nullable=True, comment='VLLM 파인튜닝 작업 ID'))
    op.create_index('idx_batch_key_vllm_task_id', 'BATCH_KEY', ['vllm_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_batch_key_vllm_task_id', table_name='BATCH_KEY')
    op.drop_column('BATCH_KEY', 'vllm_task_id')
    # ### end Alembic commands ###