"""add image_option to AIInfluencer

Revision ID: 2fe2c079ad33
Revises: dca38644aa50
Create Date: 2025-06-30 17:53:24.692062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe2c079ad33'
down_revision = 'dca38644aa50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AI_INFLUENCER', sa.Column('image_option', sa.Boolean(), nullable=True, comment='이미지 생성 옵션'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AI_INFLUENCER', 'image_option')
    # ### end Alembic commands ###
