"""Add extra_metadata column to generated_images

Revision ID: 5653b4a3f6cb
Revises: add_generated_images_001
Create Date: 2025-07-25 18:14:51.669837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5653b4a3f6cb'
down_revision = 'add_generated_images_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_group_id', table_name='IMAGE_STORAGE')
    op.drop_table('IMAGE_STORAGE')
    op.alter_column('AI_INFLUENCER_MCP_SERVER', 'influencer_id',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='인플루언서 고유 식별자',
               existing_nullable=False)
    op.alter_column('AI_INFLUENCER_MCP_SERVER', 'mcp_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='MCP서버 고유식별자',
               existing_nullable=False)
    op.drop_constraint('AI_INFLUENCER_MCP_SERVER_ibfk_2', 'AI_INFLUENCER_MCP_SERVER', type_='foreignkey')
    op.drop_constraint('AI_INFLUENCER_MCP_SERVER_ibfk_1', 'AI_INFLUENCER_MCP_SERVER', type_='foreignkey')
    op.create_foreign_key(None, 'AI_INFLUENCER_MCP_SERVER', 'AI_INFLUENCER', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'AI_INFLUENCER_MCP_SERVER', 'MCP_SERVER', ['mcp_id'], ['mcp_id'])
    op.drop_index('idx_batch_key_vllm_task_id', table_name='BATCH_KEY')
    op.alter_column('BOARD', 'group_id',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='그룹 고유 식별자',
               existing_nullable=False)
    op.alter_column('BOARD', 'board_status',
               existing_type=mysql.INTEGER(),
               comment='1:임시저장, 2:예약상태, 3:발행됨',
               existing_comment='1:임시저장, 2:발행됨',
               existing_nullable=False)
    op.alter_column('BOARD', 'published_at',
               existing_type=mysql.TIMESTAMP(),
               comment='실제 발행 시간',
               existing_comment='게시물 발행 시각',
               existing_nullable=True)
    op.alter_column('BOARD', 'platform_post_id',
               existing_type=mysql.VARCHAR(length=255),
               comment='각 플랫폼에 업로드된 게시글의 post ID (인스타그램, 페이스북, 블로그 등)',
               existing_nullable=True)
    op.drop_constraint('BOARD_ibfk_2', 'BOARD', type_='foreignkey')
    op.create_foreign_key(None, 'BOARD', 'USER_GROUP', ['user_id', 'group_id'], ['user_id', 'group_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('HF_TOKEN_MANAGE', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_comment='그룹의 기본 토큰 여부',
               existing_nullable=False)
    op.alter_column('MCP_SERVER', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('MCP_SERVER', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('STYLE_PRESET', 'system_prompt',
               existing_type=mysql.TEXT(),
               nullable=False,
               existing_comment='인플루언서 시스템 프롬프트')
    op.alter_column('USER', 'pod_status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_comment='Pod 상태: none, starting, ready, processing',
               existing_nullable=True)
    op.alter_column('USER', 'session_created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='세션 생성 시간',
               existing_nullable=True)
    op.alter_column('USER', 'session_expires_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='세션 만료 시간 (15분)',
               existing_nullable=True)
    op.alter_column('USER', 'processing_expires_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='처리 만료 시간 (10분)',
               existing_nullable=True)
    op.alter_column('USER', 'total_generations',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='총 이미지 생성 횟수',
               existing_nullable=True)
    op.add_column('generated_images', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    op.alter_column('generated_images', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_generated_images_id'), 'generated_images', ['id'], unique=False)
    op.drop_column('generated_images', 'metadata')
    op.alter_column('generated_voice', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('voice_base', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('voice_base', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_base', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('voice_base', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('generated_voice', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.add_column('generated_images', sa.Column('metadata', mysql.JSON(), nullable=True))
    op.drop_index(op.f('ix_generated_images_id'), table_name='generated_images')
    op.alter_column('generated_images', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('generated_images', 'extra_metadata')
    op.alter_column('USER', 'total_generations',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_comment='총 이미지 생성 횟수',
               existing_nullable=True)
    op.alter_column('USER', 'processing_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_comment='처리 만료 시간 (10분)',
               existing_nullable=True)
    op.alter_column('USER', 'session_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_comment='세션 만료 시간 (15분)',
               existing_nullable=True)
    op.alter_column('USER', 'session_created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_comment='세션 생성 시간',
               existing_nullable=True)
    op.alter_column('USER', 'pod_status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'none'"),
               existing_comment='Pod 상태: none, starting, ready, processing',
               existing_nullable=True)
    op.alter_column('STYLE_PRESET', 'system_prompt',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_comment='인플루언서 시스템 프롬프트')
    op.alter_column('MCP_SERVER', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('MCP_SERVER', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('HF_TOKEN_MANAGE', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='그룹의 기본 토큰 여부',
               existing_nullable=False)
    op.drop_constraint(None, 'BOARD', type_='foreignkey')
    op.create_foreign_key('BOARD_ibfk_2', 'BOARD', 'USER_GROUP', ['user_id', 'team_id'], ['user_id', 'group_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('BOARD', 'platform_post_id',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='각 플랫폼에 업로드된 게시글의 post ID (인스타그램, 페이스북, 블로그 등)',
               existing_nullable=True)
    op.alter_column('BOARD', 'published_at',
               existing_type=mysql.TIMESTAMP(),
               comment='게시물 발행 시각',
               existing_comment='실제 발행 시간',
               existing_nullable=True)
    op.alter_column('BOARD', 'board_status',
               existing_type=mysql.INTEGER(),
               comment='1:임시저장, 2:발행됨',
               existing_comment='1:임시저장, 2:예약상태, 3:발행됨',
               existing_nullable=False)
    op.alter_column('BOARD', 'group_id',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_comment='그룹 고유 식별자',
               existing_nullable=False)
    op.create_index('idx_batch_key_vllm_task_id', 'BATCH_KEY', ['vllm_task_id'], unique=False)
    op.drop_constraint(None, 'AI_INFLUENCER_MCP_SERVER', type_='foreignkey')
    op.drop_constraint(None, 'AI_INFLUENCER_MCP_SERVER', type_='foreignkey')
    op.create_foreign_key('AI_INFLUENCER_MCP_SERVER_ibfk_1', 'AI_INFLUENCER_MCP_SERVER', 'AI_INFLUENCER', ['influencer_id'], ['influencer_id'], ondelete='CASCADE')
    op.create_foreign_key('AI_INFLUENCER_MCP_SERVER_ibfk_2', 'AI_INFLUENCER_MCP_SERVER', 'MCP_SERVER', ['mcp_id'], ['mcp_id'], ondelete='CASCADE')
    op.alter_column('AI_INFLUENCER_MCP_SERVER', 'mcp_id',
               existing_type=mysql.INTEGER(),
               comment='MCP서버 고유식별자',
               existing_nullable=False)
    op.alter_column('AI_INFLUENCER_MCP_SERVER', 'influencer_id',
               existing_type=mysql.VARCHAR(length=255),
               comment='인플루언서 고유 식별자',
               existing_nullable=False)
    op.create_table('IMAGE_STORAGE',
    sa.Column('storage_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='이미지 저장 고유 식별자'),
    sa.Column('s3_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000), nullable=False, comment='S3 이미지 URL'),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='그룹 ID'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='생성 시간'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='수정 시간'),
    sa.ForeignKeyConstraint(['group_id'], ['TEAM.group_id'], name='IMAGE_STORAGE_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('storage_id'),
    comment='이미지 저장 테이블 - S3 URL과 그룹 ID만 관리',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='이미지 저장 테이블 - S3 URL과 그룹 ID만 관리',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_group_id', 'IMAGE_STORAGE', ['group_id'], unique=False)
    # ### end Alembic commands ###
