"""add mbti_id, system_prompt, influencer_description to style_preset

Revision ID: 7063dbfd8e74
Revises: eb119f73480e
Create Date: 2025-07-16 17:32:12.765014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7063dbfd8e74'
down_revision = 'eb119f73480e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('STYLE_PRESET', sa.Column('mbti_id', sa.Integer(), nullable=True, comment='MBTI 성격 고유 식별자'))
    op.add_column('STYLE_PRESET', sa.Column('system_prompt', sa.Text(), nullable=False, comment='인플루언서 시스템 프롬프트'))
    op.add_column('STYLE_PRESET', sa.Column('influencer_description', sa.Text(), nullable=False, comment='인플루언서 설명'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('STYLE_PRESET', 'influencer_description')
    op.drop_column('STYLE_PRESET', 'system_prompt')
    op.drop_column('STYLE_PRESET', 'mbti_id')
    # ### end Alembic commands ###
