"""remove unnecessary instagram fields from aiinfluencer

Revision ID: 74e1f866a4cb
Revises: c0c54cb6d3e8
Create Date: 2025-07-01 15:50:27.056845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74e1f866a4cb'
down_revision = 'c0c54cb6d3e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AI_INFLUENCER', 'instagram_website')
    op.drop_column('AI_INFLUENCER', 'instagram_username')
    op.drop_column('AI_INFLUENCER', 'instagram_name')
    op.drop_column('AI_INFLUENCER', 'instagram_biography')
    op.drop_column('AI_INFLUENCER', 'instagram_follows_count')
    op.drop_column('AI_INFLUENCER', 'instagram_account_type')
    op.drop_column('AI_INFLUENCER', 'instagram_followers_count')
    op.drop_column('AI_INFLUENCER', 'instagram_profile_picture_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AI_INFLUENCER', sa.Column('instagram_profile_picture_url', mysql.TEXT(), nullable=True, comment='인스타그램 프로필 사진 URL'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_followers_count', mysql.INTEGER(), autoincrement=False, nullable=True, comment='인스타그램 팔로워 수'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_account_type', mysql.VARCHAR(length=50), nullable=True, comment='인스타그램 계정 타입 (PERSONAL, BUSINESS, CREATOR)'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_follows_count', mysql.INTEGER(), autoincrement=False, nullable=True, comment='인스타그램 팔로잉 수'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_biography', mysql.TEXT(), nullable=True, comment='인스타그램 바이오그래피'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_name', mysql.VARCHAR(length=255), nullable=True, comment='인스타그램 실명'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_username', mysql.VARCHAR(length=100), nullable=True, comment='인스타그램 사용자명'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_website', mysql.VARCHAR(length=255), nullable=True, comment='인스타그램 웹사이트'))
    # ### end Alembic commands ###
