"""add influencer_personality to AIInfluencer

Revision ID: 7fda0eb4ca0c
Revises: 939abea1dc4c
Create Date: 2025-06-30 17:51:19.706426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fda0eb4ca0c'
down_revision = '939abea1dc4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AI_INFLUENCER', sa.Column('influencer_personality', sa.Text(), nullable=True, comment='AI 인플루언서 성격'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AI_INFLUENCER', 'influencer_personality')
    # ### end Alembic commands ###
