"""Create GENERATED_TONE table

Revision ID: 8daeff3811d0
Revises: 6d8d941d18ff
Create Date: 2025-07-06 23:57:02.905157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8daeff3811d0'
down_revision = '6d8d941d18ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GENERATED_TONE',
    sa.Column('tone_id', sa.String(length=255), nullable=False, comment='생성된 어투 고유 식별자'),
    sa.Column('influencer_id', sa.String(length=255), nullable=False, comment='인플루언서 고유 식별자'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='어투 제목 (예: 말투 1)'),
    sa.Column('example', sa.Text(), nullable=False, comment='어투 예시 대화'),
    sa.Column('tone_description', sa.String(length=255), nullable=False, comment='어투 설명'),
    sa.Column('hashtags', sa.String(length=255), nullable=True, comment='어투 관련 해시태그'),
    sa.Column('system_prompt', sa.Text(), nullable=False, comment='어투 생성에 사용된 시스템 프롬프트'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='마지막 수정 시각'),
    sa.ForeignKeyConstraint(['influencer_id'], ['AI_INFLUENCER.influencer_id'], ),
    sa.PrimaryKeyConstraint('tone_id')
    )
    op.drop_index('idx_content_enhancements_enhancement_id', table_name='content_enhancements')
    op.drop_index('idx_content_enhancements_user_id', table_name='content_enhancements')
    op.drop_table('content_enhancements')
    op.alter_column('AI_INFLUENCER', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 시각',
               existing_nullable=False)
    op.alter_column('AI_INFLUENCER', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='마지막 수정 시각',
               existing_nullable=False)
    op.drop_constraint('fk_ai_influencer_hf_manage_id', 'AI_INFLUENCER', type_='foreignkey')
    op.create_foreign_key(None, 'AI_INFLUENCER', 'HF_TOKEN_MANAGE', ['hf_manage_id'], ['hf_manage_id'])
    op.alter_column('BOARD', 'board_status',
               existing_type=mysql.INTEGER(),
               comment='1:임시저장, 2:발행됨',
               existing_comment='0:최초생성, 1:임시저장, 2:예약, 3:발행됨',
               existing_nullable=False)
    op.alter_column('BOARD', 'published_at',
               existing_type=mysql.TIMESTAMP(),
               comment='게시물 발행 시각',
               existing_comment='실제 발행 시간',
               existing_nullable=True)
    op.alter_column('BOARD', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment='생성 시각',
               existing_comment='게시글 생성 시각',
               existing_nullable=False)
    op.alter_column('BOARD', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment='마지막 수정 시각',
               existing_nullable=False)
    op.create_foreign_key(None, 'BOARD', 'USER_GROUP', ['user_id', 'team_id'], ['user_id', 'group_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('BOARD', 'reservation_at')
    op.drop_column('BOARD', 'group_id')
    op.alter_column('HF_TOKEN_MANAGE', 'group_id',
               existing_type=mysql.INTEGER(),
               comment='그룹 고유 식별자 (NULL 가능 - 할당되지 않은 토큰)',
               existing_nullable=True)
    op.alter_column('HF_TOKEN_MANAGE', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 시각',
               existing_nullable=False)
    op.alter_column('HF_TOKEN_MANAGE', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('INFLUENCER_API', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 시각',
               existing_nullable=False)
    op.alter_column('INFLUENCER_API', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('STYLE_PRESET', 'influencer_hairstyle',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_comment='인플루언서 헤어 스타일',
               existing_nullable=False)
    op.alter_column('STYLE_PRESET', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 시각',
               existing_nullable=False)
    op.alter_column('STYLE_PRESET', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('TEAM', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 시각',
               existing_nullable=False)
    op.alter_column('TEAM', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('USER', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 시각',
               existing_nullable=False)
    op.alter_column('USER', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='마지막 수정 시각',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USER', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('USER', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('TEAM', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('TEAM', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('STYLE_PRESET', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('STYLE_PRESET', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('STYLE_PRESET', 'influencer_hairstyle',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=500),
               existing_comment='인플루언서 헤어 스타일',
               existing_nullable=False)
    op.alter_column('INFLUENCER_API', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('INFLUENCER_API', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('HF_TOKEN_MANAGE', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('HF_TOKEN_MANAGE', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('HF_TOKEN_MANAGE', 'group_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='그룹 고유 식별자 (NULL 가능 - 할당되지 않은 토큰)',
               existing_nullable=True)
    op.add_column('BOARD', sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='그룹 고유 식별자'))
    op.add_column('BOARD', sa.Column('reservation_at', mysql.TIMESTAMP(), nullable=True, comment='게시글 예약 발행 일시'))
    op.drop_constraint(None, 'BOARD', type_='foreignkey')
    op.alter_column('BOARD', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('BOARD', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='게시글 생성 시각',
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('BOARD', 'published_at',
               existing_type=mysql.TIMESTAMP(),
               comment='실제 발행 시간',
               existing_comment='게시물 발행 시각',
               existing_nullable=True)
    op.alter_column('BOARD', 'board_status',
               existing_type=mysql.INTEGER(),
               comment='0:최초생성, 1:임시저장, 2:예약, 3:발행됨',
               existing_comment='1:임시저장, 2:발행됨',
               existing_nullable=False)
    op.drop_constraint(None, 'AI_INFLUENCER', type_='foreignkey')
    op.create_foreign_key('fk_ai_influencer_hf_manage_id', 'AI_INFLUENCER', 'HF_TOKEN_MANAGE', ['hf_manage_id'], ['hf_manage_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('AI_INFLUENCER', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='마지막 수정 시각',
               existing_nullable=False)
    op.alter_column('AI_INFLUENCER', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.create_table('content_enhancements',
    sa.Column('enhancement_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('original_content', mysql.TEXT(), nullable=False),
    sa.Column('enhanced_content', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('openai_model', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('openai_tokens_used', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('openai_cost', mysql.FLOAT(), nullable=True),
    sa.Column('board_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('influencer_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('enhancement_prompt', mysql.TEXT(), nullable=True),
    sa.Column('improvement_notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('approved_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('enhancement_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_content_enhancements_user_id', 'content_enhancements', ['user_id'], unique=False)
    op.create_index('idx_content_enhancements_enhancement_id', 'content_enhancements', ['enhancement_id'], unique=False)
    op.drop_table('GENERATED_TONE')
    # ### end Alembic commands ###
