"""add influencer_description to AIInfluencer

Revision ID: 939abea1dc4c
Revises: a3ee0a28016b
Create Date: 2025-06-30 17:50:25.347867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939abea1dc4c'
down_revision = 'a3ee0a28016b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AI_INFLUENCER', sa.Column('influencer_description', sa.Text(), nullable=True, comment='AI 인플루언서 설명'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AI_INFLUENCER', 'influencer_description')
    # ### end Alembic commands ###
