"""Initial migration with Team model fixed

Revision ID: a3ee0a28016b
Revises: 
Create Date: 2025-06-30 17:48:58.736799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ee0a28016b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('API_CALL_AGGREGATION',
    sa.Column('api_call_id', sa.String(length=255), nullable=False, comment='API호출 집계 고유 식별자'),
    sa.Column('api_id', sa.String(length=255), nullable=False, comment='API 고유 식별자'),
    sa.Column('influencer_id', sa.String(length=255), nullable=False, comment='모델 고유 식별자'),
    sa.Column('daily_call_count', sa.Integer(), nullable=False, comment='일일 API 호출 횟수'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='일일 API 집계 데이터 생성일'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='일일 API 집계 데이터 수정일'),
    sa.ForeignKeyConstraint(['api_id'], ['INFLUENCER_API.api_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_call_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('API_CALL_AGGREGATION')
    # ### end Alembic commands ###
