"""add instagram api login fields to aiinfluencer

Revision ID: c0c54cb6d3e8
Revises: 2fe2c079ad33
Create Date: 2025-07-01 15:44:21.000406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c54cb6d3e8'
down_revision = '2fe2c079ad33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AI_INFLUENCER', sa.Column('instagram_token_expires_at', sa.TIMESTAMP(), nullable=True, comment='인스타그램 액세스 토큰 만료 일시'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_name', sa.String(length=255), nullable=True, comment='인스타그램 실명'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_biography', sa.Text(), nullable=True, comment='인스타그램 바이오그래피'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_followers_count', sa.Integer(), nullable=True, comment='인스타그램 팔로워 수'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_follows_count', sa.Integer(), nullable=True, comment='인스타그램 팔로잉 수'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_profile_picture_url', sa.Text(), nullable=True, comment='인스타그램 프로필 사진 URL'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_website', sa.String(length=255), nullable=True, comment='인스타그램 웹사이트'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AI_INFLUENCER', 'instagram_website')
    op.drop_column('AI_INFLUENCER', 'instagram_profile_picture_url')
    op.drop_column('AI_INFLUENCER', 'instagram_follows_count')
    op.drop_column('AI_INFLUENCER', 'instagram_followers_count')
    op.drop_column('AI_INFLUENCER', 'instagram_biography')
    op.drop_column('AI_INFLUENCER', 'instagram_name')
    op.drop_column('AI_INFLUENCER', 'instagram_token_expires_at')
    # ### end Alembic commands ###
