"""ensure voice_option in AIInfluencer

Revision ID: dca38644aa50
Revises: 0e00f2507597
Create Date: 2025-06-30 17:52:54.570097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca38644aa50'
down_revision = '0e00f2507597'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AI_INFLUENCER', sa.Column('voice_option', sa.Boolean(), nullable=True, comment='음성 생성 옵션'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AI_INFLUENCER', 'voice_option')
    # ### end Alembic commands ###
