"""Add QA generation count to BatchKey

Revision ID: f08b0c6efa35
Revises: 74e1f866a4cb
Create Date: 2025-07-03 09:28:42.160041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f08b0c6efa35'
down_revision = '74e1f866a4cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BATCH_KEY_task_id'), table_name='BATCH_KEY')
    op.drop_index(op.f('ix_BATCH_KEY_openai_batch_id'), table_name='BATCH_KEY')
    op.drop_column('BATCH_KEY', 'completed_at')
    op.drop_column('BATCH_KEY', 'updated_at')
    op.drop_column('BATCH_KEY', 'created_at')
    op.drop_column('BATCH_KEY', 'is_finetuning_started')
    op.drop_column('BATCH_KEY', 'is_uploaded_to_s3')
    op.drop_column('BATCH_KEY', 'is_processed')
    op.drop_column('BATCH_KEY', 's3_processed_file_url')
    op.drop_column('BATCH_KEY', 's3_qa_file_url')
    op.drop_column('BATCH_KEY', 'error_message')
    op.drop_column('BATCH_KEY', 'output_file_id')
    op.drop_column('BATCH_KEY', 'input_file_id')
    op.drop_column('BATCH_KEY', 'generated_qa_pairs')
    op.drop_column('BATCH_KEY', 'total_qa_pairs')
    op.drop_column('BATCH_KEY', 'status')
    op.drop_column('BATCH_KEY', 'openai_batch_id')
    op.drop_column('BATCH_KEY', 'task_id')
    op.add_column('AI_INFLUENCER', sa.Column('instagram_followers_count', mysql.INTEGER(), autoincrement=False, nullable=True, comment='인스타그램 팔로워 수'))
    op.add_column('AI_INFLUENCER', sa.Column('instagram_profile_picture_url', mysql.TEXT(), nullable=True, comment='인스타그램 프로필 사진 URL'))
    # ### end Alembic commands ###
