"""Add reservation_at and published_at to board

Revision ID: g09c1d7fgb46
Revises: f08b0c6efa35
Create Date: 2025-07-06 03:15:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'g09c1d7fgb46'
down_revision = 'f08b0c6efa35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BOARD', sa.Column('reservation_at', sa.TIMESTAMP(), nullable=True, comment='예약 발행 시간'))
    op.add_column('BOARD', sa.Column('published_at', sa.TIMESTAMP(), nullable=True, comment='실제 발행 시간'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BOARD', 'published_at')
    op.drop_column('BOARD', 'reservation_at')
    # ### end Alembic commands ###